server:
  port: 8081
spring:
  application:
    name: user-service
  main:
    banner-mode: off
  # Datasource config settings
  datasource:
    url: jdbc:mysql://localhost:10035/user_database
    username: root
    password: root
  # JPA/Hibernate config settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
